version: '3.9'
services:
  app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 121212
      DB_NAME: user_service

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 121212
      MYSQL_DATABASE: user_service
      MYSQL_ROOT_HOST: "%"

